### ISSUE TITLE
Implement role based authentication

### ISSUE THREAD

**Issue by TouhidZaman** [TouhidZaman/jobboardbdFE#1]
## Task Description

- [x] Use Firebase Auth
- [x] Store additional user data to the backend 
- [x] You must use redux to run firebase functions  and to store the auth state
