### ISSUE TITLE
Implement add new job functionalities and view all/individual jobs

### ISSUE THREAD

**Issue by TouhidZaman** [TouhidZaman/jobboardbdFE#3]
## Task Details 

- [x] Post new job data to the backend
- [x] fetch all jobs from the backend and display them on the jobs page
- [x] After clicking the details button on each job will navigate to the individual job view page and view all the details in this page
